# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntityAllocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, allocation_date_time: datetime=None, allocation_type: str=None, num_allocations: int=None, allocated_by_profile: str=None):  # noqa: E501
        """EntityAllocation - a model defined in Swagger

        :param allocation_date_time: The allocation_date_time of this EntityAllocation.  # noqa: E501
        :type allocation_date_time: datetime
        :param allocation_type: The allocation_type of this EntityAllocation.  # noqa: E501
        :type allocation_type: str
        :param num_allocations: The num_allocations of this EntityAllocation.  # noqa: E501
        :type num_allocations: int
        :param allocated_by_profile: The allocated_by_profile of this EntityAllocation.  # noqa: E501
        :type allocated_by_profile: str
        """
        self.swagger_types = {
            'allocation_date_time': datetime,
            'allocation_type': str,
            'num_allocations': int,
            'allocated_by_profile': str
        }

        self.attribute_map = {
            'allocation_date_time': 'allocationDateTime',
            'allocation_type': 'allocationType',
            'num_allocations': 'numAllocations',
            'allocated_by_profile': 'allocatedByProfile'
        }

        self._allocation_date_time = allocation_date_time
        self._allocation_type = allocation_type
        self._num_allocations = num_allocations
        self._allocated_by_profile = allocated_by_profile

    @classmethod
    def from_dict(cls, dikt) -> 'EntityAllocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EntityAllocation of this EntityAllocation.  # noqa: E501
        :rtype: EntityAllocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def allocation_date_time(self) -> datetime:
        """Gets the allocation_date_time of this EntityAllocation.


        :return: The allocation_date_time of this EntityAllocation.
        :rtype: datetime
        """
        return self._allocation_date_time

    @allocation_date_time.setter
    def allocation_date_time(self, allocation_date_time: datetime):
        """Sets the allocation_date_time of this EntityAllocation.


        :param allocation_date_time: The allocation_date_time of this EntityAllocation.
        :type allocation_date_time: datetime
        """

        self._allocation_date_time = allocation_date_time

    @property
    def allocation_type(self) -> str:
        """Gets the allocation_type of this EntityAllocation.

        The allocation type - whether it's for appreciation, yearly volunteers, past participants, etc  # noqa: E501

        :return: The allocation_type of this EntityAllocation.
        :rtype: str
        """
        return self._allocation_type

    @allocation_type.setter
    def allocation_type(self, allocation_type: str):
        """Sets the allocation_type of this EntityAllocation.

        The allocation type - whether it's for appreciation, yearly volunteers, past participants, etc  # noqa: E501

        :param allocation_type: The allocation_type of this EntityAllocation.
        :type allocation_type: str
        """

        self._allocation_type = allocation_type

    @property
    def num_allocations(self) -> int:
        """Gets the num_allocations of this EntityAllocation.


        :return: The num_allocations of this EntityAllocation.
        :rtype: int
        """
        return self._num_allocations

    @num_allocations.setter
    def num_allocations(self, num_allocations: int):
        """Sets the num_allocations of this EntityAllocation.


        :param num_allocations: The num_allocations of this EntityAllocation.
        :type num_allocations: int
        """

        self._num_allocations = num_allocations

    @property
    def allocated_by_profile(self) -> str:
        """Gets the allocated_by_profile of this EntityAllocation.

        The profile id it's allocated by  # noqa: E501

        :return: The allocated_by_profile of this EntityAllocation.
        :rtype: str
        """
        return self._allocated_by_profile

    @allocated_by_profile.setter
    def allocated_by_profile(self, allocated_by_profile: str):
        """Sets the allocated_by_profile of this EntityAllocation.

        The profile id it's allocated by  # noqa: E501

        :param allocated_by_profile: The allocated_by_profile of this EntityAllocation.
        :type allocated_by_profile: str
        """

        self._allocated_by_profile = allocated_by_profile
